//CSS Imports
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cormorant_Garamond, Inter } from "next/font/google";
import "../globals.css";
// import Header from "../src/components/header";

// import Header from "./../src/components/header";
import Footer from "./../src/components/Footer"

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-serif", // This creates a CSS variable we can use
  weight: ["300", "400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// Metadata
export const metadata: Metadata = {
  title: "Salon and Co.",
  description: "Generated by create next app",
};

// HTML type layout
export default function RootLayout({
  // Children Prop
  children,
  // Specify Properties of children, in this case 'read-only'
}: Readonly<{
  children: React.ReactNode;
}>)
 {
return (
    <>
      {/* <Header /> */}
      <main>{children}</main>
      <Footer />
    </>
  );
}
